Repository s-hamann/desec-dns, pull requests merged in 2024-06, with the labels that each got.

#9 Poetry / Publishing on PyPi
  .gitignore
  pyproject.toml
  requirements.txt
Labels: enhancement

#11 Add GitHub Actions code quality workflow
  .github/workflows/code_quality.yml
  .github/workflows/matchers/mypy.json
  .github/workflows/matchers/ruff.json
Labels: enhancement

#10 Add --verbose to CLI
  README.md
  desec.py
Labels: enhancement

#13 Add installation notes to Readme.md
  README.md
Labels: enhancement

#21 Documentation improvements
  .github/workflows/docs.yml
  README.md
  desec.py
Labels: enhancement

#22 Code Quality workflow improvements
  .github/workflows/code_quality.yml
  tox.ini
Labels: ci/cd

#23 Make TLSAField.valid_values an immutable tuple
  desec.py
Labels: technical debt

#24 Refactor list concatenation in add-tlsa/set-tlsa subcommand
  desec.py
Labels: technical debt

#25 Drop assert in APIClient.parse_links()
  desec.py
Labels: technical debt

#26 Add request_timeout to APIClient
  desec.py
Labels: enhancement

#28 Set target Python version for ruff
  pyproject.toml
Labels: tests

#30 Type checks: Replace outdated types-cryptography with cryptography
  tox.ini
Labels: technical debt, tests

#29 Use timezone-aware datetimes in certificate checks
  desec.py
  pyproject.toml
Labels: technical debt

#31 Expand ~ in --token-file argument
  desec.py
Labels: bug

#32 Change default path of token file to match the XDG Base Directory Specification
  README.md
  desec.py
Labels: enhancement, breaking change

#33 Make CLI related functions and classes private
  desec.py
Labels: technical debt

#34 Fix CLI entrypoint in pyproject.toml
  pyproject.toml
Labels: bug
